server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



# static mapping
#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#
#            # Inventory Service
#            - id: inventory-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/inventory/**
#
#            # Order Service
#            - id: order-service
#              uri: http://localhost:8081
#              predicates:
#                - Path=/order/**


#  Eureka + lb:// (DYNAMIC)
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Inventory Service
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**

            # Order Service
            - id: order-service
              uri: lb://order-service
              filters:
                - AddRequestHeader=X-test-color,red
              predicates:
                - Path=/order/**
